version: "3.5"

services:
  portfolio-v2:
   container_name: portfolio-v2
   image: gabrielsoaresdev/portfolio-v2:latest
   ports:
    - "3000:3000"
   restart: always
  networks:
   - proxy-reverse-network
networks:
  proxy-reverse-network:
   name: proxy-reverse-network
   external: true
