/* eslint-disable @next/next/no-page-custom-font */
import React from 'react'
import '@/app/global.css'
import Head from 'next/head'
import NavBar from '@/components/Layout/NavBar'
import PageContextProvider from '@/context/PageContext/PageContext'
import Footer from '@/components/Layout/Footer'

export const metadata = {
  title: 'Gabriel Soares Maciel',
  description: 'Generated by create next app',
}

export default function RootLayout({
  children,
}: {
  children: React.ReactNode
}) {
  return (
    <html lang="pt-br">
      <Head>
        <meta charSet="utf-8" />
        <meta httpEquiv="X-UA-Compatible" content="IE=edge" />

        <title>{metadata.title}</title>
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <body>
        <NavBar />
        <PageContextProvider>{children}</PageContextProvider>
        <Footer />
      </body>
    </html>
  )
}
